### PR TITLE
Update for Discourse v2.x

### LINKED ISSUE #1: Error when installing on Discourse v2.0.0.beta9
My ruby is inadequate, so I would appreciate some help!  Relevant log output:

`````I, [2018-05-06T21:47:19.961098 #13]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
rake aborted!
NoMethodError: undefined method `before_filter' for DiscourseMailgun::MailgunController:Class
Did you mean?  before_action
/var/www/discourse/plugins/discourse-mailgun/plugin.rb:43:in `<class:MailgunController>'
/var/www/discourse/plugins/discourse-mailgun/plugin.rb:42:in `block in activate!'
/var/www/discourse/lib/plugin/instance.rb:271:in `block in notify_after_initialize'
/var/www/discourse/lib/plugin/instance.rb:269:in `each'
/var/www/discourse/lib/plugin/instance.rb:269:in `notify_after_initialize'
/var/www/discourse/config/application.rb:237:in `each'
/var/www/discourse/config/application.rb:237:in `block in <class:Application>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `public_send'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/railtie.rb:185:in `method_missing'
/var/www/discourse/config/environment.rb:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
I, [2018-05-06T21:47:26.173902 #13]  INFO -- : 
I, [2018-05-06T21:47:26.174589 #13]  INFO -- : Terminating async processes

FAILED
--------------------
Pups::ExecError: cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate' failed with return #<Process::Status: pid 392 exit 1>
Location of failure: /pups/lib/pups/exec_command.rb:108:in `spawn'
exec failed with the params {"cd"=>"$home", "hook"=>"bundle_exec", "cmd"=>["su discourse -c 'bundle install --deployment --verbose --without test --without development --retry 3 --jobs 4'", "su discourse -c 'bundle exec rake db:migrate'", "su discourse -c 'bundle exec rake assets:precompile'"]}
32f6a7720a11981869f2555de8df1c0d96cca005dab2f2c7777ed66e207c0e57
** FAILED TO BOOTSTRAP ** please scroll up and look for earlier error messages, there may be more than one
````

Please advise if there is further info I can provide, and thank you!

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This updates the plugin to work with Discourse v2.x, and cleans up some now-unused config settings as well.

Fixes #1

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@halkeye yeah it seemed like it would work, and I figured, with the extra few tweaks to clean up the config, it might be nice to kick it back up to the original.

Unfortunately, it seems that the `/mailgun/incoming` route isn’t added properly (anymore?), so it doesn’t _quite_ work.

Any suggestions?

**Comment by halkeye** [comment]
I haven't used it in a while, but how are you checking. I can check my install when I get home.

**Comment by jeffbyrnes** [comment]
So yeah, when I try to add the route to Mailgun, it errors out & says that the forward URL “needs to be publicly accessible”.

When I attempt to `curl https://$my_domain/mailgun/incoming`, I get a 404. So something is a little different with Discourse, maybe? I’m running Discourse 2.4.0.beta1 (discourse/discourse@4f97f85178b197e99240b3b7f2c2c0c251d4c39b)

**Comment by halkeye** [comment]
Try curl -X post instead of just curl. I don't think it's exposed on get. Also is your domain publically accessible?

**Comment by halkeye** [comment]
```
 (ssh) odin  ~  curl -X POST https://discourse.gavinmogan.com/mailgun/incoming -v 2>&1 | grep HTTP
> POST /mailgun/incoming HTTP/1.1
< HTTP/1.1 401 Unauthorized

 (ssh) odin  ~  curl https://discourse.gavinmogan.com/mailgun/incoming -v 2>&1 | grep HTTP
> GET /mailgun/incoming HTTP/1.1
< HTTP/1.1 404 Not Found
```

```
/bin/sh -- -c 'cd /var/www/discourse; rails routes | grep mailgun -i'
                           webhooks_mailgun POST     /webhooks/mailgun(.:format)                                                                   webhooks#mailgun
                          discourse_mailgun          /mailgun                                                                                      DiscourseMailgun::Engine
Routes for DiscourseMailgun::Engine:
incoming POST /incoming(.:format) discourse_mailgun/mailgun#incoming
Time: 0h:00m:04s
```

**Comment by jeffbyrnes** [comment]
Heh, yah, `POST`-ing did the trick; and I forgot about `rails routes`, thanks for the reminder! Been a while since I dealt with Rails so directly :)

So yeah, the route is there, and I’ve got it all working on my Discourse setup!

So this PR is all good & validated as working.

**Pull request closed without merging**
